# Generated by Django 4.1.7 on 2023-05-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Codigos',
            },
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=5, unique=True)),
                ('ocupacion', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mueble', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('ACC', 'ACC')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penetrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(default=None, max_length=5, unique=True)),
                ('ocupacion', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Psicotropico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=5, unique=True)),
                ('ocupacion', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=5, unique=True)),
                ('ocupacion', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=4)),
                ('fecha_vencimiento', models.DateField()),
                ('lote', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('mueble', models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('ACC', 'ACC')], max_length=10, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(default='img/default_prod.png', upload_to='img/img-productos')),
                ('ubicacionE', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Racks.estanteria', to_field='ubicacion')),
                ('ubicacionF', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Racks.penetrable', to_field='ubicacion')),
                ('ubicacionP', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Racks.psicotropico', to_field='ubicacion')),
                ('ubicacionS', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Racks.suplemento', to_field='ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
