# Generated by Django 4.1.1 on 2023-03-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racksfrente',
            name='articulo',
            field=models.ForeignKey(max_length=60, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='Racks.productos'),
        ),
    ]
