# Generated by Django 4.1.7 on 2023-05-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0002_alter_codigo_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Codigo',
        ),
    ]
