# Generated by Django 4.1.7 on 2023-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0003_delete_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Codigos',
            },
        ),
    ]
