# Generated by Django 4.1.7 on 2023-05-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0004_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulo',
        ),
    ]
