# Generated by Django 4.1.7 on 2023-05-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0007_alter_mueble_mueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
