# Generated by Django 4.1.7 on 2023-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0008_articulo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimaEjecucion', models.DateTimeField()),
            ],
        ),
    ]
