# Generated by Django 4.1.7 on 2023-05-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0009_ultimaejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='mueble',
            field=models.CharField(blank=True, choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('M4', 'M4'), ('ACC', 'ACC'), ('SUP', 'SUP'), ('PSI', 'PSI')], max_length=10, null=True),
        ),
    ]
