# Generated by Django 4.1.7 on 2023-06-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0010_alter_productos_mueble'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='img/default_prod.png', upload_to='img/img-productos')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Racks.articulo')),
            ],
        ),
    ]
