# Generated by Django 4.1.7 on 2023-06-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Racks', '0011_imagenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Racks.articulo'),
        ),
    ]
